import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { View, Text, FlatList, Pressable, ScrollView, StyleSheet, RefreshControl, Alert, ActivityIndicator } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuth } from '../../src/context/AuthContext';
import { useSubscription } from '../../src/context/SubscriptionContext';
import { supabase } from '../../src/lib/supabase';
import { recipeService } from '../../src/services/recipeService';
import { inventoryService } from '../../src/services/inventoryService';
import { RecipeImage, prefetchRecipeImages, matchTone } from '../../src/components/RecipeImage';
import { colors, radii, spacing, shadow } from '../../src/theme';
import { useFloatingTabBar } from '../../src/hooks/useFloatingTabBar';
import type { RecipeWithIngredients } from '../../src/types';
import { ChefHat, Clock3, Users, Sparkles, Trash2, Bookmark, ArrowRight, Zap } from 'lucide-react-native';
import { EmptyState, ItemImage, UpgradeNotice, StatusPill, colorWithOpacity, type Status } from '../../src/components/ui';
import { usePageGutter } from '../../src/hooks/useContentLayout';
import {
  productGroups, recipesForProduct, isFilipino, isNearExpiry,
  type PantryItem, type ProductGroup,
} from '../../src/utils/pantryRecipes';

const RECIPE_CATEGORIES = ['All', 'Meals', 'Desserts', 'Snacks', 'Beverages'] as const;

/** How many dishes to ask for. The server clamps this to 3–8. */
const RECIPE_COUNT = 6;

/**
 * Whether the automatic first generation has already been tried in this run of
 * the app.
 *
 * Module-level rather than a ref: the tab remounts as the user moves around, and
 * re-asking the model on every visit to an empty pantry would spend an AI call
 * each time for an answer that has not changed. A restart is a fair moment to
 * try again — the pantry may have been filled in the meantime.
 */
let autoGeneratedThisSession = false;

const EMPTY_HINT = 'Add what you have to Inventory and we\'ll build recipes around it.';

/** "just now" / "4h ago" / "2d ago" — enough precision for a caption. */
function relativeTime(iso: string): string {
  const minutes = Math.floor((Date.now() - Date.parse(iso)) / 60_000);
  if (!Number.isFinite(minutes) || minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

function localDateKey(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export default function RecipesScreen() {
  // One gutter for the whole screen. The list, the header, the chip row and the
  // caption each used to carry their own — the list at one value and everything
  // else at another, so the first recipe card sat eight points left of the title
  // above it.
  const { gutter } = usePageGutter();
  const { profile } = useAuth();
  const { gates, refresh: refreshEntitlements } = useSubscription();
  const insets = useSafeAreaInsets();
  // The bottom nav floats over this screen, so the list has to end above it.
  const { contentInset } = useFloatingTabBar();
  const [recipes, setRecipes] = useState<RecipeWithIngredients[]>([]);
  const [weeklySavings, setWeeklySavings] = useState<number | null>(null);
  /**
   * The pantry, for the product chips. Read alongside the recipes rather than
   * off them: a recipe carries the *ids* of the items it uses, and a chip needs
   * the name and the photo.
   *
   * Only stock in hand — a consumed item is not something the user can cook with,
   * so offering "recipes for the chicken you ate last week" would be a dead end.
   */
  const [items, setItems] = useState<PantryItem[]>([]);
  const nearExpiryItems = useMemo(() => items.filter(isNearExpiry), [items]);
  const nearExpiryIds = useMemo(() => new Set(nearExpiryItems.map((item) => item.id)), [nearExpiryItems]);
  const nearExpiryRecipes = useMemo(
    () => recipes.filter((recipe) => recipe.inventory_item_ids.some((id) => nearExpiryIds.has(id))),
    [nearExpiryIds, recipes],
  );
  const [category, setCategory] = useState<string>('All');
  /** The selected product chip, by inventory item id. */
  const [product, setProduct] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [clearing, setClearing] = useState(false);
  const [emptyHint, setEmptyHint] = useState(EMPTY_HINT);
  /** Set when the server refuses for want of allowance, which `gates` may not know yet. */
  const [limitReached, setLimitReached] = useState(false);
  const fetchRecipes = useCallback(async () => {
    if (!profile) return;
    try {
      const now = new Date();
      const weekStart = new Date(now);
      weekStart.setDate(now.getDate() - now.getDay());
      weekStart.setHours(0, 0, 0, 0);
      const [rows, inventory, savingsResult] = await Promise.all([
        recipeService.getRecipes(profile.id),
        inventoryService.getInventory(profile.id),
        supabase.rpc('calculate_estimated_savings', {
          user_id: profile.id,
          start_date: localDateKey(weekStart),
          end_date: localDateKey(now),
        }),
      ]);
      setRecipes(rows);
      if (savingsResult.error) {
        console.warn('Could not load weekly recipe savings estimate:', savingsResult.error.message);
        setWeeklySavings(null);
      } else {
        setWeeklySavings(Number(savingsResult.data ?? 0));
      }
      setItems(
        inventory
          .filter((i) => i.status === 'available')
          .map((i) => ({
            id: i.id,
            product_name: i.product_name,
            category: i.category,
            image_url: i.image_url,
            expiration_date: i.expiration_date,
            status: i.status,
          })),
      );
      // Warm the photos that are still below the fold so scrolling doesn't wait
      // on several downloads at once.
      prefetchRecipeImages(rows.map((r) => r.image_url));
    } catch (error) {
      console.error('Error fetching recipes:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [profile]);

  useEffect(() => { fetchRecipes(); }, [fetchRecipes]);

  const generate = useCallback(async (requested?: string) => {
    if (generating) return;
    if (nearExpiryItems.length === 0) {
      setEmptyHint('No available products are expiring within 7 days. Recipes will appear here when an item is nearing expiry.');
      return;
    }
    setGenerating(true);
    try {
      const result = await recipeService.generateRecipes({
        category: requested && requested !== 'All' ? requested.toLowerCase() : undefined,
        count: RECIPE_COUNT,
      });

      if (result.status === 'ok') {
        setEmptyHint(EMPTY_HINT);
        await fetchRecipes();
        return;
      }

      if (result.status === 'nothing_to_cook') {
        // Not a failure — an honest answer about an empty kitchen.
        setEmptyHint(
          'Your pantry is empty, so there was nothing to build a recipe from. Add a few items to Inventory and try again.',
        );
        return;
      }

      if (result.status === 'limit_reached') {
        setLimitReached(true);
        // The server is the authority on the allowance and it just refused, so
        // the cached entitlements are behind. Refreshing replaces the notice's
        // copy with the real gate's, including the count and the tier to buy.
        await refreshEntitlements();
        return;
      }

      Alert.alert(
        'Couldn\'t generate recipes',
        'The recipe service didn\'t answer. Check your connection and try again — you weren\'t charged a scan.',
      );
    } finally {
      setGenerating(false);
    }
  }, [fetchRecipes, generating, nearExpiryItems.length, refreshEntitlements]);

  // First visit with no current expiring-item recipes: generate once so the tab
  // is never simply blank. Only when the plan allows it.
  useEffect(() => {
    if (!profile || loading || generating) return;
    if (nearExpiryItems.length === 0 || nearExpiryRecipes.length > 0 || autoGeneratedThisSession) return;
    if (!gates.aiScan.allowed) return;
    autoGeneratedThisSession = true;
    generate();
  }, [profile, loading, generating, nearExpiryItems.length, nearExpiryRecipes.length, gates.aiScan.allowed, generate]);

  const confirmGenerate = useCallback(() => {
    const replaces = recipes.length > 0;
    // A full generation covers products as well as categories, which is several
    // model calls rather than one. The dialog says so rather than letting a long
    // spinner be the only warning.
    const scope = category === 'All'
      ? 'It builds recipes only around products expiring within 7 days.'
      : `It writes ${category.toLowerCase()} dishes only for products expiring within 7 days.`;

    Alert.alert(
      replaces ? 'Generate new recipes?' : 'Generate recipes?',
      `This uses one AI scan and ${replaces ? 'replaces your current suggestions' : 'builds dishes around food that needs to be used soon'}. ${scope}${
        replaces ? ' Recipes you\'ve favourited are kept.' : ''
      }`,
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Generate', onPress: () => generate(category) },
      ],
    );
  }, [category, generate, recipes.length]);

  const clearSuggestions = useCallback(() => {
    if (!profile || recipes.length === 0 || clearing) return;
    Alert.alert(
      'Clear recipe suggestions?',
      'AI suggestions will be removed. Favorited recipes will stay saved.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Clear',
          style: 'destructive',
          onPress: async () => {
            setClearing(true);
            try {
              await recipeService.clearAISuggestions(profile.id);
              setRecipes([]);
              setProduct(null);
              setCategory('All');
            } catch (error) {
              console.error('Error clearing recipe suggestions:', error);
              Alert.alert('Couldn\'t clear suggestions', 'Please try again.');
            } finally {
              setClearing(false);
            }
          },
        },
      ],
    );
  }, [clearing, profile, recipes.length]);

  /** The product chip row: every pantry item with at least one recipe. */
  const groups = useMemo(() => productGroups(nearExpiryItems, nearExpiryRecipes), [nearExpiryItems, nearExpiryRecipes]);

  /**
   * The selected product, or null.
   *
   * Resolved against the current groups rather than trusted as-is: a generation
   * replaces the recipe set, so a product selected a moment ago can have nothing
   * left under it. Falling back to "no product" shows the whole list, which is a
   * better answer than an empty one for a chip the user can no longer see.
   */
  const activeProduct = product && groups.some((g) => g.id === product) ? product : null;

  const activeGroup = activeProduct ? groups.find((g) => g.id === activeProduct) ?? null : null;

  // Both narrowings apply: the chips are one question ("what can I cook with
  // this") and the categories another ("what kind of dish"), and a user who has
  // set both means both.
  const visible = useMemo(() => {
    const forProduct = activeProduct ? recipesForProduct(activeProduct, nearExpiryRecipes) : nearExpiryRecipes;
    return category === 'All'
      ? forProduct
      : forProduct.filter((r) => r.category === category.toLowerCase());
  }, [activeProduct, category, nearExpiryRecipes]);

  const generatedAt = useMemo(
    () =>
      recipes.reduce<string | null>((newest, r) => {
        if (!r.generated_at) return newest;
        return !newest || r.generated_at > newest ? r.generated_at : newest;
      }, null),
    [recipes],
  );

  const showUpgrade = !gates.aiScan.allowed || limitReached;
  // `allowed()` carries no wording, so a refusal the cached entitlements have not
  // caught up with yet falls back to its own copy rather than rendering blank.
  const upgradeTitle = gates.aiScan.allowed ? 'AI scan limit reached' : gates.aiScan.title;
  const upgradeMessage = gates.aiScan.allowed
    ? 'You have used all your AI scans for this month. Upgrade for more, or generate again next month.'
    : gates.aiScan.message;
  const subtitle = generatedAt
    ? `From your pantry · generated ${relativeTime(generatedAt)}`
    : 'Recipes for products expiring within 7 days';

  const renderRecipe = ({ item }: { item: RecipeWithIngredients }) => {
    const uses = item.ingredient_names.slice(0, 3).join(', ');
    const totalMinutes = item.prep_time + (item.cook_time ?? 0);
    const filipino = isFilipino(item);
    const matchStatus: Status =
      item.match_percent !== null && item.match_percent >= 75
        ? 'fresh'
        : item.match_percent !== null && item.match_percent >= 40
        ? 'expiringSoon'
        : 'active';

    return (
      <Pressable
        style={({ pressed }) => [styles.card, pressed && { opacity: 0.92 }]}
        onPress={() => router.push({ pathname: '/recipes/[id]', params: { id: item.id } })}
      >
        <View style={styles.cardImageWrap}>
          <RecipeImage uri={item.image_url} category={item.category} width="100%" height={168} radius={0} />
          <StatusPill
            status={matchStatus}
            label={`${item.match_percent ?? 0}% Pantry Match`}
            style={styles.matchBadge}
          />
          <View style={styles.categoryLabel}>
            <Text style={styles.categoryLabelText}>{filipino ? 'Filipino Comfort' : `${item.category || 'Meal'} idea`}</Text>
          </View>
        </View>
        <View style={styles.cardContent}>
          <View style={styles.cardTitleRow}>
            <Text style={styles.name}>{item.name}</Text>
            <Bookmark size={20} color={colors.textSecondary} strokeWidth={1.8} />
          </View>
          <View style={styles.metaRow}>
            <View style={styles.metaItem}>
              <Clock3 size={13} color={colors.textSecondary} strokeWidth={1.8} />
              <Text style={styles.metaText}>{totalMinutes} min</Text>
            </View>
            <View style={styles.metaItem}>
              <Users size={13} color={colors.textSecondary} strokeWidth={1.8} />
              <Text style={styles.metaText}>{item.servings} servings</Text>
            </View>
            <Text style={styles.metaDot}>•</Text>
            <Text style={styles.difficulty}>{item.difficulty}</Text>
          </View>
          <View style={[styles.usePanel, matchStatus === 'expiringSoon' && styles.usePanelWarning]}>
            <Text style={styles.useText}>
              <Text style={styles.useCheck}>✓ </Text>
              Uses: {uses || item.description}
            </Text>
            {item.match_percent !== null && item.match_percent < 75 && (
              <Text style={styles.missingText}>⚠ Missing ingredients may be needed</Text>
            )}
          </View>
          <View style={styles.cardActionRow}>
            <Zap size={15} color={colors.surface} fill={colors.surface} strokeWidth={2.3} />
            <Text style={styles.cardActionText}>{item.match_percent !== null && item.match_percent < 75 ? 'View Recipe' : 'View Recipe & Cook'}</Text>
            <ArrowRight size={15} color={colors.surface} strokeWidth={2.5} />
          </View>
        </View>
      </Pressable>
    );
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top + 6 }]}>
      <View style={[styles.header, { paddingHorizontal: gutter }]}>
        <View style={{ flex: 1 }}>
          <Text style={styles.title}>AI Recipe Ideas</Text>
          <Text style={styles.subtitle}>Made with ingredients from your fridge & pantry</Text>
        </View>
        <View style={styles.headerActions}>
          <Pressable
            onPress={clearSuggestions}
            disabled={clearing || recipes.length === 0}
            hitSlop={8}
            accessibilityRole="button"
            accessibilityLabel="Clear recipe suggestions"
            style={({ pressed }) => [
              styles.clearBtn,
              (clearing || recipes.length === 0) && { opacity: 0.35 },
              pressed && { opacity: 0.7 },
            ]}
          >
            {clearing
              ? <ActivityIndicator size="small" color={colors.danger} />
              : <Trash2 size={18} color={colors.danger} strokeWidth={2.2} />}
          </Pressable>
          <Pressable
            onPress={confirmGenerate}
            disabled={generating || showUpgrade}
            hitSlop={8}
            style={({ pressed }) => [
              styles.generateBtn,
              (generating || showUpgrade) && { opacity: 0.45 },
              pressed && { opacity: 0.7 },
            ]}
          >
            {generating
              ? <ActivityIndicator size="small" color={colors.primary} />
              : <><Sparkles size={15} color={colors.primary} strokeWidth={2.2} /><Text style={styles.generateText}>Regenerate</Text></>}
          </Pressable>
        </View>
      </View>

      {/* Category filters use the same card treatment as the pantry products below. */}
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.categoryScroll}
        contentContainerStyle={[styles.categoryRow, { paddingHorizontal: gutter }]}
      >
        {RECIPE_CATEGORIES.map((cat) => (
          <CategoryChip
            key={cat}
            label={cat}
            active={category === cat}
            onPress={() => setCategory(cat)}
          />
        ))}
      </ScrollView>

      {/* The product row. Scrolled horizontally rather than wrapped, because a
          full pantry has more items than a wrapped row can hold without pushing
          the list off the screen — and the count on each chip is what makes the
          row worth scrolling: the items with the most to offer come first. */}
      {groups.length > 0 && (
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          style={styles.productScroll}
          contentContainerStyle={[styles.productRow, { paddingHorizontal: gutter }]}
        >
          {groups.map((group) => (
            <ProductChip
              key={group.id}
              group={group}
              active={activeProduct === group.id}
              // Tapping the selected chip again clears it, so the row can always
              // get back to "everything" without a separate control.
              onPress={() => setProduct(activeProduct === group.id ? null : group.id)}
            />
          ))}
        </ScrollView>
      )}

      {showUpgrade && (
        <UpgradeNotice
          title={upgradeTitle}
          message={upgradeMessage}
          onPress={() => router.push('/subscription')}
          style={{ marginHorizontal: gutter, marginBottom: spacing.md }}
        />
      )}

      {activeGroup && (
        <Text style={[styles.productCaption, { paddingHorizontal: gutter }]}>
          {activeGroup.count > visible.length
            ? `Top ${visible.length} of ${activeGroup.count} for ${activeGroup.name}`
            : `${visible.length} for ${activeGroup.name}`}
          {visible.some(isFilipino) ? ' · Filipino dishes first' : ''}
        </Text>
      )}

      {generating && (
        <View style={[styles.generatingCard, { marginHorizontal: gutter }]}>
          <ActivityIndicator color={colors.primary} />
          <View style={{ flex: 1 }}>
            <Text style={styles.generatingTitle}>Checking expiring products…</Text>
            <Text style={styles.generatingText}>
              Choosing dishes around what&apos;s about to expire. This takes a moment.
            </Text>
          </View>
        </View>
      )}

      <FlatList
        style={styles.recipeList}
        data={visible}
        keyExtractor={(item) => item.id}
        renderItem={renderRecipe}
        ListHeaderComponent={(
          <View>
            <View style={styles.instantBanner}>
              <View style={styles.instantHeader}>
                <View style={styles.instantIcon}><Zap size={15} color={colors.mintBg} fill={colors.mintBg} /></View>
              <Text style={styles.instantEyebrow}>USE SOON</Text>
              </View>
              <Text style={styles.instantTitle}>{visible.length || RECIPE_COUNT} recipe ideas for products expiring soon</Text>
              <View style={styles.instantFooter}>
                <Text style={styles.instantFootText}>• Focused on items due within 7 days</Text>
                <Text style={styles.instantSavings}>
                  {weeklySavings == null
                    ? 'Savings estimate unavailable'
                    : `Est. pantry savings ${new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 0 }).format(weeklySavings)} this week`}
                </Text>
              </View>
            </View>
          </View>
        )}
        contentContainerStyle={{ paddingHorizontal: gutter, paddingBottom: contentInset, gap: spacing.sm }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); fetchRecipes(); }} colors={[colors.primary]} tintColor={colors.primary} />}
        ListEmptyComponent={
          loading || generating ? null : (
            <EmptyState
              icon={ChefHat}
              // A product chip is selected, so "no recipes yet" would be the wrong
              // story: there are recipes, just none for this item and chip
              // together. Naming both narrowings is what makes the way out
              // obvious.
              title={
                activeGroup
                  ? `No ${category === 'All' ? '' : `${category.toLowerCase()} `}recipes for ${activeGroup.name}`
                  : category === 'All' ? 'No recipes yet' : `No ${category.toLowerCase()} yet`
              }
              hint={
                activeGroup
                  ? category === 'All'
                    ? emptyHint
                    : `Nothing in ${category.toLowerCase()} uses ${activeGroup.name}. Try another chip, or clear it to see everything.`
                  : category === 'All'
                    ? nearExpiryItems.length === 0
                      ? 'No available products are expiring within 7 days. Recipe suggestions will appear here when an item is nearing expiry.'
                      : emptyHint
                    : `Nothing in ${category.toLowerCase()} yet. Generate a set and anything that fits will appear here.`
              }
              actionLabel={
                showUpgrade || nearExpiryItems.length === 0
                  ? undefined
                  : category === 'All' ? 'Generate expiring item recipes' : `Generate ${category.toLowerCase()}`
              }
              onAction={showUpgrade || nearExpiryItems.length === 0 ? undefined : () => generate(category)}
            />
          )
        }
      />
    </View>
  );
}

/* --------------------------------------------------------------- product chip */

function CategoryChip({
  label,
  active,
  onPress,
}: {
  label: string;
  active: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [
        styles.productChip,
        styles.categoryChip,
        active && styles.productChipActive,
        pressed && { opacity: 0.8 },
      ]}
      accessibilityRole="button"
      accessibilityState={{ selected: active }}
      accessibilityLabel={`${label} recipe category`}
    >
      <View style={[styles.categoryChipIcon, active && styles.categoryChipIconActive]}>
        <ChefHat size={14} color={active ? colors.primaryDark : colors.primary} strokeWidth={2.3} />
      </View>
      <Text style={[styles.productChipText, active && styles.productChipTextActive]}>
        {label}
      </Text>
    </Pressable>
  );
}

/**
 * One item in the product row.
 *
 * Shows the item's own photo through `ItemImage`, the same component the
 * inventory list uses, so a food looks the same in both places. The count is the
 * chip's reason for being — it says how much is behind the tap before the user
 * makes it.
 */
function ProductChip({
  group,
  active,
  onPress,
}: {
  group: ProductGroup;
  active: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [
        styles.productChip,
        active && styles.productChipActive,
        pressed && { opacity: 0.8 },
      ]}
      accessibilityRole="button"
      accessibilityState={{ selected: active }}
      accessibilityLabel={`${group.name}, ${group.count} ${group.count === 1 ? 'recipe' : 'recipes'}`}
    >
      <ItemImage uri={group.imageUrl} category={group.category} size={22} radius={11} />
      <Text
        style={[styles.productChipText, active && styles.productChipTextActive]}
        numberOfLines={2}
      >
        {group.name}
      </Text>
      <Text style={[styles.productChipCount, active && styles.productChipTextActive]}>
        {group.count}
      </Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.screenBg },
  header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingBottom: spacing.md },
  title: { fontSize: 26, fontWeight: '800', color: colors.textPrimary },
  subtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  generateBtn: {
    height: 36, borderRadius: radii.pill,
    paddingHorizontal: 12,
    backgroundColor: colors.mintBg, borderWidth: 1, borderColor: colors.primary,
    flexDirection: 'row', gap: 5, alignItems: 'center', justifyContent: 'center',
  },
  generateText: { color: colors.primaryDark, fontSize: 12, fontWeight: '700' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  clearBtn: {
    width: 42, height: 42, borderRadius: 21,
    backgroundColor: colorWithOpacity(colors.danger, 0.1), alignItems: 'center', justifyContent: 'center',
  },
  // Both chip rows are horizontal scrollers inside a column that also holds the
  // list. `flexGrow: 0` keeps each one at its content height: without it a
  // ScrollView is free to take a share of the column, which stretches the row
  // and squeezes the list below it. The margin lives on the scroller rather than
  // on its content container, where it would move the chips inside the scroll
  // area instead of moving the row.
  recipeList: { flex: 1, zIndex: 0 },
  categoryScroll: { flexGrow: 0, zIndex: 2, elevation: 2 },
  categoryRow: { gap: spacing.sm, minHeight: 42, alignItems: 'center', paddingVertical: spacing.xs, paddingBottom: spacing.sm },
  productScroll: { flexGrow: 0, zIndex: 2, elevation: 2 },
  productRow: { gap: spacing.sm, minHeight: 42, alignItems: 'center', paddingVertical: spacing.xs, paddingBottom: spacing.sm },
  productChip: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: colors.surface, borderRadius: radii.pill,
    paddingVertical: 5, paddingLeft: 5, paddingRight: 12,
    borderWidth: 1, borderColor: colors.border,
  },
  categoryChip: { paddingLeft: 8, paddingRight: 14 },
  categoryChipIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mintBg,
  },
  categoryChipIconActive: { backgroundColor: colors.surface },
  productChipActive: { backgroundColor: colors.mintBg, borderColor: colors.primary },
  productChipText: { flexShrink: 1, maxWidth: 220, fontSize: 13, lineHeight: 16, fontWeight: '600', color: colors.textPrimary },
  productChipTextActive: { color: colors.primaryDark, fontWeight: '800' },
  productChipCount: { fontSize: 11.5, fontWeight: '700', color: colors.textSecondary },
  productCaption: {
    fontSize: 12, color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  generatingCard: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    backgroundColor: colors.surface, borderRadius: radii.lg,
    padding: spacing.md, marginBottom: spacing.md,
    ...shadow.card,
  },
  generatingTitle: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  generatingText: { fontSize: 12, color: colors.textSecondary, marginTop: 2, lineHeight: 17 },
  instantBanner: {
    backgroundColor: colors.primaryDark,
    borderRadius: radii.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  instantHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  instantIcon: {
    width: 24, height: 24, borderRadius: 12,
    backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center',
  },
  instantEyebrow: { color: colors.mintBg, fontSize: 12, fontWeight: '800', letterSpacing: 0.5 },
  instantTitle: { color: colors.surface, fontSize: 16, lineHeight: 22, fontWeight: '800', marginTop: spacing.sm },
  instantFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, marginTop: spacing.lg },
  instantFootText: { flex: 1, color: colors.mintBg, fontSize: 11.5 },
  instantSavings: { color: colors.surface, backgroundColor: colors.primary, borderRadius: radii.pill, paddingHorizontal: 10, paddingVertical: 7, fontSize: 11, fontWeight: '800' },
  card: {
    width: '100%', minWidth: 0, overflow: 'hidden',
    backgroundColor: colors.surface, borderRadius: radii.lg,
    ...shadow.card,
  },
  cardImageWrap: { width: '100%', height: 168, position: 'relative' },
  matchBadge: { position: 'absolute', top: spacing.sm, right: spacing.sm, backgroundColor: colors.primary, color: colors.surface },
  categoryLabel: { position: 'absolute', left: spacing.sm, bottom: spacing.sm, backgroundColor: colors.surface, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4 },
  categoryLabelText: { fontSize: 11, fontWeight: '700', color: colors.textPrimary },
  cardContent: { minWidth: 0, padding: spacing.md, gap: spacing.sm },
  cardTitleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  name: { flex: 1, minWidth: 0, fontSize: 16, lineHeight: 21, fontWeight: '800', color: colors.textPrimary },
  metaRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
  metaDot: { color: colors.textSecondary, fontSize: 12 },
  difficulty: {
    fontSize: 11, fontWeight: '700', color: colors.primary, textTransform: 'capitalize',
  },
  usePanel: { backgroundColor: colors.mintBg, borderRadius: radii.md, padding: spacing.sm },
  usePanelWarning: { backgroundColor: '#FFF4D6' },
  useText: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 17, color: colors.textPrimary, fontWeight: '500' },
  useCheck: { color: colors.primary, fontWeight: '800' },
  missingText: { color: '#A16207', fontSize: 11, marginTop: 3 },
  cardActionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: colors.primaryDark, borderRadius: radii.pill, paddingVertical: 10 },
  cardActionText: { color: colors.surface, fontSize: 12, fontWeight: '800' },
});
