import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { View, Text, FlatList, Pressable, StyleSheet, RefreshControl, Alert, ActivityIndicator } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuth } from '../../src/context/AuthContext';
import { useSubscription } from '../../src/context/SubscriptionContext';
import { recipeService } from '../../src/services/recipeService';
import { RecipeImage, prefetchRecipeImages, matchTone } from '../../src/components/RecipeImage';
import { COLORS, SPACING, RADII, SHADOW } from '../../src/theme';
import type { RecipeWithIngredients } from '../../src/types';
import { ChefHat, Clock3, Users, Sparkles } from 'lucide-react-native';
import { Chip, EmptyState, StatusBadge, UpgradeNotice } from '../../src/components/ui';

const RECIPE_CATEGORIES = ['All', 'Meals', 'Desserts', 'Snacks', 'Beverages'] as const;

/** How many dishes to ask for. The server clamps this to 3–8. */
const RECIPE_COUNT = 6;

/**
 * Whether the automatic first generation has already been tried in this run of
 * the app.
 *
 * Module-level rather than a ref: the tab remounts as the user moves around, and
 * re-asking the model on every visit to an empty pantry would spend an Anthropic
 * call each time for an answer that has not changed. A restart is a fair moment
 * to try again — the pantry may have been filled in the meantime.
 */
let autoGeneratedThisSession = false;

const EMPTY_HINT = 'Add what you have to Inventory and we\'ll build recipes around it.';

/** "just now" / "4h ago" / "2d ago" — enough precision for a caption. */
function relativeTime(iso: string): string {
  const minutes = Math.floor((Date.now() - Date.parse(iso)) / 60_000);
  if (!Number.isFinite(minutes) || minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export default function RecipesScreen() {
  const { profile } = useAuth();
  const { gates, refresh: refreshEntitlements } = useSubscription();
  const insets = useSafeAreaInsets();
  const [recipes, setRecipes] = useState<RecipeWithIngredients[]>([]);
  const [category, setCategory] = useState<string>('All');
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [emptyHint, setEmptyHint] = useState(EMPTY_HINT);
  /** Set when the server refuses for want of allowance, which `gates` may not know yet. */
  const [limitReached, setLimitReached] = useState(false);

  const fetchRecipes = useCallback(async () => {
    if (!profile) return;
    try {
      const rows = await recipeService.getRecipes(profile.id);
      setRecipes(rows);
      // Warm the photos that are still below the fold so scrolling doesn't wait
      // on several downloads at once.
      prefetchRecipeImages(rows.map((r) => r.image_url));
    } catch (error) {
      console.error('Error fetching recipes:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [profile]);

  useEffect(() => { fetchRecipes(); }, [fetchRecipes]);

  const generate = useCallback(async (requested?: string) => {
    if (generating) return;
    setGenerating(true);
    try {
      const result = await recipeService.generateRecipes({
        category: requested && requested !== 'All' ? requested.toLowerCase() : undefined,
        count: RECIPE_COUNT,
      });

      if (result.status === 'ok') {
        setEmptyHint(EMPTY_HINT);
        await fetchRecipes();
        return;
      }

      if (result.status === 'nothing_to_cook') {
        // Not a failure — an honest answer about an empty kitchen.
        setEmptyHint(
          'Your pantry is empty, so there was nothing to build a recipe from. Add a few items to Inventory and try again.',
        );
        return;
      }

      if (result.status === 'limit_reached') {
        setLimitReached(true);
        // The server is the authority on the allowance and it just refused, so
        // the cached entitlements are behind. Refreshing replaces the notice's
        // copy with the real gate's, including the count and the tier to buy.
        await refreshEntitlements();
        return;
      }

      Alert.alert(
        'Couldn\'t generate recipes',
        'The recipe service didn\'t answer. Check your connection and try again — you weren\'t charged a scan.',
      );
    } finally {
      setGenerating(false);
    }
  }, [fetchRecipes, generating, refreshEntitlements]);

  // First visit on an account with no recipes: generate once so the tab is never
  // simply blank. Only when the plan allows it — otherwise the empty state offers
  // the upgrade instead.
  useEffect(() => {
    if (!profile || loading || generating) return;
    if (recipes.length > 0 || autoGeneratedThisSession) return;
    if (!gates.aiScan.allowed) return;
    autoGeneratedThisSession = true;
    generate();
  }, [profile, loading, generating, recipes.length, gates.aiScan.allowed, generate]);

  const confirmGenerate = useCallback(() => {
    Alert.alert(
      recipes.length > 0 ? 'Generate new recipes?' : 'Generate recipes?',
      recipes.length > 0
        ? `This uses one AI scan and replaces your current suggestions. Recipes you've favourited are kept.`
        : 'This uses one AI scan and builds a set of dishes from what you have in your pantry right now.',
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Generate', onPress: () => generate(category) },
      ],
    );
  }, [category, generate, recipes.length]);

  const visible = useMemo(
    () =>
      category === 'All'
        ? recipes
        : recipes.filter((r) => r.category === category.toLowerCase()),
    [category, recipes],
  );

  const generatedAt = useMemo(
    () =>
      recipes.reduce<string | null>((newest, r) => {
        if (!r.generated_at) return newest;
        return !newest || r.generated_at > newest ? r.generated_at : newest;
      }, null),
    [recipes],
  );

  const showUpgrade = !gates.aiScan.allowed || limitReached;
  // `allowed()` carries no wording, so a refusal the cached entitlements have not
  // caught up with yet falls back to its own copy rather than rendering blank.
  const upgradeTitle = gates.aiScan.allowed ? 'AI scan limit reached' : gates.aiScan.title;
  const upgradeMessage = gates.aiScan.allowed
    ? 'You have used all your AI scans for this month. Upgrade for more, or generate again next month.'
    : gates.aiScan.message;
  const subtitle = generatedAt
    ? `From your pantry · generated ${relativeTime(generatedAt)}`
    : 'Turn expiring ingredients into meals';

  const renderRecipe = ({ item }: { item: RecipeWithIngredients }) => {
    const uses = item.ingredient_names.slice(0, 3).join(', ');
    const totalMinutes = item.prep_time + (item.cook_time ?? 0);
    return (
      <Pressable
        style={({ pressed }) => [styles.card, pressed && { opacity: 0.92 }]}
        onPress={() => router.push({ pathname: '/recipes/[id]', params: { id: item.id } })}
      >
        <RecipeImage uri={item.image_url} category={item.category} width={74} height={74} />
        <View style={{ flex: 1 }}>
          <View style={styles.nameRow}>
            <Text style={styles.name} numberOfLines={1}>{item.name}</Text>
            {item.match_percent !== null && (
              <StatusBadge label={`${item.match_percent}% match`} tone={matchTone(item.match_percent)} />
            )}
          </View>
          <View style={styles.metaRow}>
            <View style={styles.metaItem}>
              <Clock3 size={13} color={COLORS.secondaryText} strokeWidth={2} />
              <Text style={styles.metaText}>{totalMinutes} min</Text>
            </View>
            <View style={styles.metaItem}>
              <Users size={13} color={COLORS.secondaryText} strokeWidth={2} />
              <Text style={styles.metaText}>{item.servings} servings</Text>
            </View>
            <Text style={styles.difficulty}>{item.difficulty}</Text>
          </View>
          {uses ? (
            <View style={styles.useRow}>
              <Text style={styles.useLabel}>Use: </Text>
              <Text style={styles.useText} numberOfLines={1}>
                {uses}{item.ingredient_names.length > 3 ? ` +${item.ingredient_names.length - 3}` : ''}
              </Text>
            </View>
          ) : (
            <Text style={styles.desc} numberOfLines={1}>{item.description}</Text>
          )}
        </View>
      </Pressable>
    );
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top + 6 }]}>
      <View style={styles.header}>
        <View style={{ flex: 1 }}>
          <Text style={styles.title}>Recipe Suggestions</Text>
          <Text style={styles.subtitle}>{subtitle}</Text>
        </View>
        <Pressable
          onPress={confirmGenerate}
          disabled={generating || showUpgrade}
          hitSlop={8}
          style={({ pressed }) => [
            styles.generateBtn,
            (generating || showUpgrade) && { opacity: 0.45 },
            pressed && { opacity: 0.7 },
          ]}
        >
          {generating
            ? <ActivityIndicator size="small" color={COLORS.primary} />
            : <Sparkles size={20} color={COLORS.primary} strokeWidth={2.2} />}
        </Pressable>
      </View>

      <View style={styles.chipRow}>
        {RECIPE_CATEGORIES.map((cat) => (
          <Chip key={cat} label={cat} active={category === cat} onPress={() => setCategory(cat)} />
        ))}
      </View>

      {showUpgrade && (
        <UpgradeNotice
          title={upgradeTitle}
          message={upgradeMessage}
          onPress={() => router.push('/subscription')}
          style={{ marginHorizontal: SPACING.lg, marginBottom: SPACING.md }}
        />
      )}

      {generating && (
        <View style={styles.generatingCard}>
          <ActivityIndicator color={COLORS.primary} />
          <View style={{ flex: 1 }}>
            <Text style={styles.generatingTitle}>Reading your pantry…</Text>
            <Text style={styles.generatingText}>
              Choosing dishes around what&apos;s about to expire. This takes a moment.
            </Text>
          </View>
        </View>
      )}

      <FlatList
        data={visible}
        keyExtractor={(item) => item.id}
        renderItem={renderRecipe}
        contentContainerStyle={{ paddingHorizontal: SPACING.lg, paddingBottom: SPACING.xl, gap: SPACING.sm }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); fetchRecipes(); }} colors={[COLORS.primary]} tintColor={COLORS.primary} />}
        ListEmptyComponent={
          loading || generating ? null : (
            <EmptyState
              icon={ChefHat}
              title={category === 'All' ? 'No recipes yet' : `No ${category.toLowerCase()} yet`}
              hint={category === 'All' ? emptyHint : `Nothing in ${category.toLowerCase()} yet. Generate a set and anything that fits will appear here.`}
              actionLabel={
                showUpgrade
                  ? undefined
                  : category === 'All' ? 'Generate from my pantry' : `Generate ${category.toLowerCase()}`
              }
              onAction={showUpgrade ? undefined : () => (category === 'All' ? generate() : generate(category))}
            />
          )
        }
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md, paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md },
  title: { fontSize: 26, fontWeight: '800', color: COLORS.text },
  subtitle: { fontSize: 13, color: COLORS.secondaryText, marginTop: 2 },
  generateBtn: {
    width: 42, height: 42, borderRadius: 21,
    backgroundColor: COLORS.primaryLight, alignItems: 'center', justifyContent: 'center',
  },
  chipRow: { flexDirection: 'row', gap: SPACING.sm, paddingHorizontal: SPACING.lg, marginBottom: SPACING.md },
  generatingCard: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    backgroundColor: COLORS.white, borderRadius: RADII.card,
    padding: SPACING.md, marginHorizontal: SPACING.lg, marginBottom: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth, borderColor: COLORS.divider,
  },
  generatingTitle: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  generatingText: { fontSize: 12, color: COLORS.secondaryText, marginTop: 2, lineHeight: 17 },
  card: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    backgroundColor: COLORS.white, borderRadius: RADII.card,
    padding: SPACING.md, ...SHADOW.card,
  },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm },
  name: { flex: 1, fontSize: 16, fontWeight: '700', color: COLORS.text },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText: { fontSize: 12, color: COLORS.secondaryText, fontWeight: '500' },
  difficulty: {
    fontSize: 11, fontWeight: '700', color: COLORS.primary, textTransform: 'capitalize',
  },
  useRow: { flexDirection: 'row', marginTop: 7 },
  useLabel: { fontSize: 12, color: COLORS.secondaryText },
  useText: { flex: 1, fontSize: 12, color: COLORS.text, fontWeight: '500' },
  desc: { fontSize: 12, color: COLORS.secondaryText, marginTop: 7 },
});
